export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const COMPANY_REPOSITORY = Symbol('COMPANY_REPOSITORY');
export const DONOR_REPOSITORY = Symbol('DONOR_REPOSITORY');

export const GET_COMPANY_BY_SLUG_USE_CASE = Symbol(
  'GET_COMPANY_BY_SLUG_USE_CASE',
);
export const UPDATE_COMPANY_USE_CASE = Symbol('UPDATE_COMPANY_USE_CASE');
export const UPDATE_COMPANY_IMAGE_USE_CASE = Symbol(
  'UPDATE_COMPANY_IMAGE_USE_CASE',
);
